### ISSUE TITLE
FEATURE REQUEST: new datasource for dns_ns_record_set

### ISSUE THREAD

**Issue by sysadmiral** [terraform-providers/terraform-provider-dns#20]
Could we add a data_source of `dns_ns_record_set` please?

This would be useful in cases where you are handling zone delegation of subdomains.

Terraform could do a lookup of a delegated domain and if the nameservers have changed then it can update any associated delegation records automatically.

**Comment by katbyte** [comment]
Hello @sysadmiral,

Is there a reason the existing [`dns_ns_record_set` data source](https://www.terraform.io/docs/providers/dns/d/dns_ns_record_set.html) doesn't meet your needs?

**Comment by sysadmiral** [comment]
It does! I think when I opened this it may not have been documented...
