### ISSUE TITLE
Creating IP addresses that do not format the same when read back fails

### ISSUE THREAD

**Issue by cdybedahl** [terraform-providers/terraform-provider-dns#23]
The `dns_a_record_set` and `dns_aaaa_record_set` resources compare IP addresses as if they were strings. This fails if the IP address requested was not written in exactly the same form as the `miekg/dns` library uses when returning it as a string. This makes Terraform emit the the `DNS record differs` error message, and leave the record created but marked as broken.

The following configuration example illustrates the problem. You will have to edit in data for a domain where you have rights to do DNS UPDATE, since I don't really feel like giving out my own update key.

    variable "dnsupdate_secret" {}
    
    provider "dns" {
      update {
        server = "ns.example.org."
        key_name = "example.org."
        key_algorithm = "hmac-sha256"
        key_secret = "${var.dnsupdate_secret}"
      }
    }
    
    resource "dns_aaaa_record_set" "works" {
      zone = "example.org."
      name = "works"
      addresses = [ "::1" ]
    }
    
    resource "dns_a_record_set" "works" {
      zone = "example.org."
      name = "works"
      addresses = [ "127.0.0.1" ]
    }
    
    resource "dns_aaaa_record_set" "fails" {
      zone = "example.org."
      name = "fails"
      addresses = [ "::0001" ]
    }
    
    resource "dns_a_record_set" "fails" {
      zone = "example.org."
      name = "fails"
      addresses = [ "127.000.000.001" ]
    }
    
Output from `terraform -v`:

    Terraform v0.11.1
    + provider.dns v1.0.0

...but I can see in the code that the problem exists as of commit 9ece5b365e9f224383176144011ea9f77325bb5f. I'll see if I can produce a patch for this, but it seems like I'll have to spend quite a bit of time understanding the innards of Terraform before I can make a good one, so please don't wait with a fix because of that :-)

**Comment by bodgit** [comment]
I raised #13 to fix this for IPv6 records nearly three months ago and have so far had no feedback. The IPv6 failure case is more obvious as you have the `::` expansion to handle; some resources return the IPv6 address in attributes fully expanded whereas `miekg/dns` compresses the address where possible so they sometimes will never match.

I can easily extend my patch to also canonicalise IPv4 addresses using the same technique.

**Comment by cdybedahl** [comment]
Yes, it was the IPv6 case that I first ran into (Digital Ocean returns IPv6 addresses for droplets in an expanded form), and when I looked into it I saw that it can happen for IPv4 as well. And it would seem to make more sense to have one patch for both problems, since they are essentially the same.

**Comment by bodgit** [comment]
I also encountered it for DO droplets :smile:

The IPv4 case is interesting as some tools will treat the zero-padding as an octal number so your example works fine but for numbers greater than `007` different tools interpret it differently. I've just checked Go and its `net.ParseIP()` [seems to just see leading zeros as padding](http://play.golang.org/p/Ti_0sZ9Rsc) rather than treat the number as octal.

See https://superuser.com/questions/857603/are-ip-addresses-with-and-without-leading-zeroes-the-same/857787 for a discussion.

**Comment by bodgit** [comment]
I've updated my PR #13 to also cover IPv4 addresses.

**Comment by apparentlymart** [comment]
Hi @cdybedahl and @bodgit!

Sorry for the slow response here. I've now merged #13, so this issue should be fixed in master.

**Comment by katbyte** [comment]
As mentioned above, looks like this was fixed by #13.

**Comment by katbyte** [comment]
Hi @cdybedahl,

Just wanted to let you know that we have released [v2.0.0](https://github.com/terraform-providers/terraform-provider-dns/blob/master/CHANGELOG.md#200-may-25-2018) of the provider containing the fix 🙂

**Comment by cdybedahl** [comment]
Excellent. Thank you!
