### ISSUE TITLE
Release 2.0.0?

### ISSUE THREAD

**Issue by bpoland** [terraform-providers/terraform-provider-dns#40]
@apparentlymart you approved some PRs a couple of weeks ago -- just wondering when we can expect a new release with those changes?

Thanks!

**Comment by bpoland** [comment]
@apparentlymart @appilon @tombuildsstuff -- would any of you guys be able to release version 2.0.0 of this provider?  We could really use some of the fixes.  Thanks!

**Comment by bpoland** [comment]
@radeksimko I notice you just made some changes to this provider -- are you able to initiate the 2.0.0 release?  Thank you!

**Comment by bpoland** [comment]
Sorry to spam but could someone please release a new version of the DNS provider?  It has been over 2 months since changes were committed.

@katbyte @apparentlymart @appilon @tombuildsstuff @vancluever

**Comment by katbyte** [comment]
Hi @bpoland,

I just released 2.0.0 this morning 🙂

**Comment by katbyte** [comment]
Also @bodgit,

You opened (and solved!) a bunch of issues so i'm just going to @ you here 🙂 Sorry it took so long to get them merged and released, thank you for all the contributions!

**Comment by bpoland** [comment]
Woohoo!  Thanks @katbyte!  And yes thank you @bodgit for your contributions!
