### ISSUE TITLE
terraform segaults when creating a dns_a_record_set resource

### ISSUE THREAD

**Issue by filterfish** [terraform-providers/terraform-provider-dns#42]
Hi there,

### Terraform Version

`Terraform v0.11.7`
`+ provider.dns v1.0.0`

I've also tried it with versions:
* `Terraform v0.10.8` &
* `Terraform v0.11.3`
  `+ provider.dns v1.0.0`

### Affected Resource(s)
Please list the resources as a list, for example:
* `dns_a_record_set`

### Terraform Configuration Files
```hcl
provider "dns" {
  update {
    server =      "192.168.8.184"
    key_name      = "terraform"
    key_algorithm = "hmac-sha256"
    /* key_secret    = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" */
  }
}

resource "dns_a_record_set" "test" {
  zone = "int.filterfish.org."
  name = "test."
  addresses = [
    "192.168.8.166"
  ]
}
```

### Debug Output

https://gist.github.com/filterfish/aa974a8579213ca184249df5bea2f698

### Panic Output

https://gist.github.com/filterfish/aa362f434b1626d3b8b934d909a43837

### Expected Behaviour
1. It should not segfault,
2. It should have created a DNS A record.

### Actual Behavior
1. It segfaulted,
2. It didn't create a DNS A record.

### Steps to Reproduce

1. `terraform apply`

The DNS server is setup properly and I can use `nsupdate` to create a record

**Comment by bpoland** [comment]
Try removing the dot at the end of the record name "test" instead of "test." and/or from the zone as well.

**Comment by filterfish** [comment]
@bpoland both need to be fully qualified or the plan won't apply:

```
Error: Error applying plan:

1 error(s) occurred:

* dns_a_record_set.test: 1 error(s) occurred:

* dns_a_record_set.test: Error creating DNS record: "zone" should be an FQDN
```

This is true for both the zone and the name.

**Comment by bpoland** [comment]
Ah okay, guess it's something more complicated then.  Hopefully a dev can take a look.

**Comment by filterfish** [comment]
I actually think this is a duplicate of #15. So I'll close this.

I should also point out that the PR on #36 fixes this.
