### ISSUE TITLE
Feature Request: Support SRV Records

### ISSUE THREAD

**Issue by bcheezum** [terraform-providers/terraform-provider-dns#45]
Hello,

Are there any plans to support SRV records with the Terraform DNS provider?

We have a use case where we are trying to dynamically build security groups in AWS. Using SRV records would simplify this process greatly.

**Comment by bodgit** [comment]
Are you after a new data source or resource? (Either way both should be implemented for consistency).

SRV records are interesting as each record is tuple of priority, weight, port and the target hostname rather than a list of just addresses. So personally, I think you'd end up wanting something like this in HCL:
```hcl
resource "dns_srv_record_set" "foo" {
  zone = "example.com."
  name = "_sip._tcp"
  ttl  = 86400

  server {
    priority = 0
    weight   = 5
    port     = 5060
    hostname = "sipserver.example.com."
  }

  server {
    ...
  }
}
```
I think you'd want something similar for MX records, which aren't supported either currently.

**Comment by bcheezum** [comment]
In this case I'm looking for a new data source, but I agree with you that both should be implemented for consistency.

My main use case would look something like this. The syntax in my example may not follow standards, and would have issues with multiple values being returned, but hopefully it makes sense.

data "dns_srv_record_set" "example" {
  host = "_service._tcp.example.com"
}

resource "aws_security_group_rule" "allow_service" {
  type                = "ingress"
  from_port       = "${data.dns_srv_record_set.example.port}"
  to_port            = "${data.dns_srv_record_set.example.port}"
  protocol          = "tcp"
  cidr_blocks     = ["${data.dns_srv_record_set.example.addrs}"]

  security_group_id = "sg-123456"
}

**Comment by jackchenquest** [comment]
Can this be marked as a enhancement ? without it, this is not a complete package.

**Comment by nhnicwaller** [comment]
It would be great to have a `dns_srv_record_set` in the Terraform DNS provider because AWS ECS can be configured to publish task addresses as SRV records, and Terraform could be used to glue that onto client services that don't support SRV records.
