### ISSUE TITLE
Reverse dns

### ISSUE THREAD

**Issue by holyhope** [terraform-providers/terraform-provider-dns#52]
Hello,

Here is a features request for a reverse dns resource.

I would like to set PTR record in arpa zone for specific ips.
This is done thanks to the [`/ip/{ip}/reverse`](https://api.ovh.com/console/#/ip/%7Bip%7D/reverse%23POST) route on APIv6.

What do you think about it?

### Terraform Version
I am using v0.11.7, but this is a features request, so...

### Affected Resource(s)
Is suggest we call it `ovh_ip` with list field called `reverse`.

### Expected Behavior
This would allow terraform to set reverse DNS for specific ips.
```terraform
resource "ovh_ip" "example_ip" {
    ip          = "${var.my_ip}"
    description = "ip to ma example service"
    reverse.    = [ "example.com" ]
}
```

### Actual Behavior
It seems impossible to set it.

### Other providers issues
Scaleway: [88](https://github.com/terraform-providers/terraform-provider-scaleway/issues/88)
HCloud: [32](https://github.com/hetznercloud/terraform-provider-hcloud/issues/32), [19](https://github.com/terraform-providers/terraform-provider-hcloud/issues/19)

**Comment by bodgit** [comment]
If I understand it correctly, this is using an update mechanism other than the one detailed in RFC 2136. Therefore I don't think it belongs in this particular provider.

Does [ovh_domain_zone_record](https://www.terraform.io/docs/providers/ovh/r/ovh_domain_zone_record.html) not do what you want?

**Comment by apparentlymart** [comment]
Hi @holyhope!

As @bodgit noted, this request seems to be specific to the `ovh` provider, rather than being a generic DNS feature. Please feel free to open an issue about this use-case in [the `ovh` provider repository](https://github.com/terraform-providers/terraform-provider-ovh), if you didn't already.
